// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercicio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("API.Models.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasEmAtraso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorCorrigido")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInicial")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("API.Models.ParametrosCalculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasEmAtraso")
                        .HasColumnType("INTEGER");

                    b.Property<double>("JurosPorDia")
                        .HasColumnType("REAL");

                    b.Property<double>("Multa")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DiasEmAtraso")
                        .IsUnique();

                    b.ToTable("ParametrosCalculo");
                });
#pragma warning restore 612, 618
        }
    }
}
